## Problem Statement

The IPL is a fast-paced T20 league, and understanding match trends can be complex. This project analyzes **ball-by-ball data (2008-2023)** to explore **batting, bowling, match results, and venue impact** using **Exploratory Data Analysis (EDA)** to uncover key insights.

### **Dataset Info:**

**Match ID** : Unique identifier for each match.

**Date**: Date on which the match was played.

**Venue** : Name of the stadium where the match was played.

**Bat First** : Name of the team that batted first.

**Bat Second** : Name of the team that batted second.

**Innings** : Indicates the inning number (1 or 2) of the match.

**Over** : Specifies the over number within the inning.

**Ball** : Denotes the ball number within the over.

**Batter** : Name of the batsman facing the delivery.

**Non Striker** : Name of the non-striking batsman.

**Bowler** : Name of the bowler delivering the ball.

**Batter Runs** : Runs scored by the batsman on that specific delivery.

**Extra Runs** : Additional runs awarded due to extras like wides or no-balls.

**Runs From Ball** : Total runs scored from that delivery (batsman + extras).

**Ball Rebowled** : Indicator if the ball was rebowled (e.g., after a no-ball).

**Extra Type** : Type of extra run conceded (e.g., wide, no-ball, leg bye, bye).

**Wicket** : Indicates if a wicket fell on that delivery (1 for yes, 0 for no).

**Method** : Type of dismissal (e.g., bowled, caught, run out, etc.).

**Player Out** : Name of the dismissed player, if applicable.

**Innings Runs** : Total runs scored in the inning up to that ball.

**Innings Wickets** : Total number of wickets lost in the inning up to that ball.

**Target Score** : The target score set by the batting team (useful in chases).

**Runs to Get** : Runs required to win the match (only in chases).

**Balls Remaining** : Number of balls left in the innings.

**Winner** : Name of the team that won the match.

**Chased Successfully** : Indicator if the target was successfully chased (1 for yes, 0 for no).

**Total Batter Runs** : The total runs accumulated by the batter up until this delivery in the innings

**Total Non Striker Runs** : The total runs accumulated by the non-striker up until this delivery in the innings

**Batter Balls Faced** : The number of valid deliveries faced by the batter up until this delivery in the innings.

**Non Striker Balls Faced** : The number of valid deliveries faced by the non-striker up until this delivery in the innings.

**Player Out Runs** : The total runs scored by the dismissed player before getting out

**Player Out Balls Faced** : The number of valid deliveries faced by the dismissed player before getting out

**Bowler Runs Conceded** : Total runs conceded by the bowler in that ball.

**Valid Ball** : Indicates if the delivery was a valid ball (not wide/no-ball).

## **Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

## **Load** **Dataset**

In [3]:
df = pd.read_csv('ball_by_ball_ipl.csv', index_col=0)

## **Dataset Overview & Structure**

In [4]:
df.head()

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,1,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,1,0,NaN,NaN,4,1
1,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,2,0,NaN,NaN,0,1
2,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,3,0,NaN,NaN,0,1
3,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,4,0,NaN,NaN,0,1
4,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,5,0,5,0,NaN,NaN,1,1

In [5]:
df.tail()

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
239688,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,1,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,16,31,9,29,NaN,NaN,2,1
239689,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,2,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,22,31,10,29,NaN,NaN,6,1
239690,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,3,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,26,31,11,29,NaN,NaN,4,1
239691,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,4,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,27,31,12,29,NaN,NaN,1,1
239692,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,5,KS Williamson,YK Pathan,...,Sunrisers Hyderabad,1,32,27,30,12,NaN,NaN,1,1

In [6]:
df.shape

(239693, 34)

In [7]:
df.size

8149562

#### **Identifying key columns and understanding data types**

In [8]:
df.columns

Index(['Match ID', 'Date', 'Venue', 'Bat First', 'Bat Second', 'Innings',
       'Over', 'Ball', 'Batter', 'Non Striker', 'Bowler', 'Batter Runs',
       'Extra Runs', 'Runs From Ball', 'Ball Rebowled', 'Extra Type', 'Wicket',
       'Method', 'Player Out', 'Innings Runs', 'Innings Wickets',
       'Target Score', 'Runs to Get', 'Balls Remaining', 'Winner',
       'Chased Successfully', 'Total Batter Runs', 'Total Non Striker Runs',
       'Batter Balls Faced', 'Non Striker Balls Faced', 'Player Out Runs',
       'Player Out Balls Faced', 'Bowler Runs Conceded', 'Valid Ball'],
      dtype='object')

In [9]:
df.dtypes

Match ID                     int64
Date                        object
Venue                       object
Bat First                   object
Bat Second                  object
Innings                      int64
Over                         int64
Ball                         int64
Batter                      object
Non Striker                 object
Bowler                      object
Batter Runs                  int64
Extra Runs                   int64
Runs From Ball               int64
Ball Rebowled                int64
Extra Type                  object
Wicket                       int64
Method                      object
Player Out                  object
Innings Runs                 int64
Innings Wickets              int64
Target Score                 int64
Runs to Get                float64
Balls Remaining              int64
Winner                      object
Chased Successfully          int64
Total Batter Runs            int64
Total Non Striker Runs       int64
Batter Balls Faced           int64
Non Striker Balls Faced      int64
Player Out Runs            float64
Player Out Balls Faced     float64
Bowler Runs Conceded         int64
Valid Ball                   int64
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 239693 entries, 0 to 239692
Data columns (total 34 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Match ID                 239693 non-null  int64
 1   Date                     239693 non-null  object
 2   Venue                    239693 non-null  object
 3   Bat First                239693 non-null  object
 4   Bat Second               239693 non-null  object
 5   Innings                  239693 non-null  int64
 6   Over                     239693 non-null  int64
 7   Ball                     239693 non-null  int64
 8   Batter                   239693 non-null  object
 9   Non Striker              239693 non-null  object
 10  Bowler                   239693 non-null  object
 11  Batter Runs              239693 non-null  int64
 12  Extra Runs               239693 non-null  int64
 13  Runs From Ball           239693 non-null  int64
 14  Ball Rebowled            239693 non-null  int64
 15  Extra Type               239693 non-null  object
 16  Wicket                   239693 non-null  int64
 17  Method                   11827 non-null   object
 18  Player Out               11827 non-null   object
 19  Innings Runs             239693 non-null  int64
 20  Innings Wickets          239693 non-null  int64
 21  Target Score             239693 non-null  int64
 22  Runs to Get              115766 non-null  float64
 23  Balls Remaining          239693 non-null  int64
 24  Winner                   239693 non-null  object
 25  Chased Successfully      239693 non-null  int64
 26  Total Batter Runs        239693 non-null  int64
 27  Total Non Striker Runs   239693 non-null  int64
 28  Batter Balls Faced       239693 non-null  int64
 29  Non Striker Balls Faced  239693 non-null  int64
 30  Player Out Runs          11827 non-null   float64
 31  Player Out Balls Faced   11827 non-null   float64
 32  Bowler Runs Conceded     239693 non-null  int64
 33  Valid Ball               239693 non-null  int64
dtypes: float64(3), int64(20), object(11)
memory usage: 64.0+ MB

In [11]:
df.describe()

,Match ID,Innings,Over,Ball,Batter Runs,Extra Runs,Runs From Ball,Ball Rebowled,Wicket,Innings Runs,...,Balls Remaining,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
count,2.396930e+05,239693.000000,239693.000000,239693.000000,239693.000000,239693.000000,239693.000000,239693.000000,239693.000000,239693.000000,...,239693.000000,239693.000000,239693.000000,239693.000000,239693.000000,239693.000000,11827.000000,11827.000000,239693.000000,239693.000000
mean,8.695839e+05,1.482976,10.199964,3.489188,1.252373,0.067198,1.319571,0.035596,0.049342,75.346426,...,61.346623,0.533774,17.180493,16.518338,13.567071,13.343681,18.753276,15.388602,1.294769,0.964404
std,3.537819e+05,0.499711,5.678629,1.708591,1.626859,0.342398,1.614630,0.185280,0.216582,48.642545,...,34.101282,0.498859,18.295757,17.799281,12.103000,12.028558,19.643315,12.867069,1.619098,0.185280
min,3.359820e+05,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483140e+05,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.000000,...,32.000000,0.000000,3.000000,3.000000,4.000000,4.000000,4.000000,5.000000,0.000000,1.000000
50%,8.298170e+05,1.000000,10.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,71.000000,...,62.000000,1.000000,11.000000,11.000000,10.000000,10.000000,12.000000,12.000000,1.000000,1.000000
75%,1.216507e+06,2.000000,15.000000,5.000000,1.000000,0.000000,1.000000,0.000000,0.000000,111.000000,...,91.000000,1.000000,26.000000,25.000000,20.000000,20.000000,28.000000,22.000000,1.000000,1.000000
max,1.370353e+06,2.000000,20.000000,7.000000,6.000000,7.000000,7.000000,1.000000,1.000000,263.000000,...,120.000000,1.000000,175.000000,175.000000,74.000000,73.000000,129.000000,71.000000,7.000000,1.000000

## **Cleaning**

###**Standardizing Categorical Data**

Before moving to analysis, ensure data
consistency in categorical values:
Checking key categorical columns prevents errors in grouping, filtering, and aggregations

In [21]:
df.select_dtypes(include=['object','category']).columns.tolist()

['Date',
 'Venue',
 'Bat First',
 'Bat Second',
 'Batter',
 'Non Striker',
 'Bowler',
 'Extra Type',
 'Method',
 'Player Out',
 'Winner']

#### **Cleaning Venue Names**

In [23]:
df['Venue'].unique()

array(['Eden Gardens', 'De Beers Diamond Oval', 'Sharjah Cricket Stadium',
       'Wankhede Stadium', 'Feroz Shah Kotla', 'Holkar Cricket Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Maharashtra Cricket Association Stadium',
       'MA Chidambaram Stadium', 'Dubai International Cricket Stadium',
       'Kingsmead', 'Dr DY Patil Sports Academy', 'SuperSport Park',
       'Sawai Mansingh Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'M Chinnaswamy Stadium', 'Rajiv Gandhi International Stadium',
       'Brabourne Stadium', 'Sheikh Zayed Stadium',
       'M.Chinnaswamy Stadium', 'Punjab Cricket Association Stadium',
       'Narendra Modi Stadium', 'Arun Jaitley Stadium',
       'Barabati Stadium', 'Saurashtra Cricket Association Stadium',
       'Sardar Patel Stadium',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Green Park', 'Subrata Roy Sahara Stadium',
       'JSCA International Stadium Complex',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Zayed Cricket Stadium', 'Vidarbha Cricket Association Stadium',
       "St George's Park",
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
       'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval',
       'Buffalo Park', 'Barsapara Cricket Stadium'], dtype=object)

In [24]:
# Standardizing Venue Names
venue_map = {
    "M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",
    "Sardar Patel Stadium": "Narendra Modi Stadium",
    "Punjab Cricket Association IS Bindra Stadium": "Punjab Cricket Association Stadium",
    "Feroz Shah Kotla": "Arun Jaitley Stadium",
    "Zayed Cricket Stadium": "Sheikh Zayed Stadium",
    "De Beers Diamond Oval": "Kimberley Oval",
    "Rajiv Gandhi International Stadium": "Uppal Stadium",
    "Dr Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "ACA-VDCA Stadium",
    "Shaheed Veer Narayan Singh International Stadium": "Raipur International Cricket Stadium",
    "JSCA International Stadium Complex": "Ranchi Stadium",
    "Barsapara Cricket Stadium": "Assam Cricket Association Stadium"
}

df["Venue"] = df["Venue"].replace(venue_map)

IPL teams wikipedia : https://en.wikipedia.org/wiki/Indian_Premier_League#:~:text=Timeline%20of%20teams

####**Cleaning Team Names**

In [25]:
df['Bat First'].unique()

array(['Chennai Super Kings', 'Rajasthan Royals', 'Mumbai Indians',
       'Delhi Daredevils', 'Royal Challengers Bangalore',
       'Delhi Capitals', 'Sunrisers Hyderabad', 'Rising Pune Supergiants',
       'Punjab Kings', 'Kings XI Punjab', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Deccan Chargers', 'Kolkata Knight Riders',
       'Gujarat Titans', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Lucknow Super Giants'], dtype=object)

In [26]:
df['Bat Second'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Delhi Capitals',
       'Kings XI Punjab', 'Kochi Tuskers Kerala', 'Delhi Daredevils',
       'Mumbai Indians', 'Gujarat Titans', 'Rajasthan Royals',
       'Royal Challengers Bangalore', 'Deccan Chargers',
       'Sunrisers Hyderabad', 'Lucknow Super Giants', 'Punjab Kings',
       'Pune Warriors', 'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant'], dtype=object)

In [27]:
df['Winner'].unique()

array(['Chennai Super Kings', 'Delhi Capitals', 'Mumbai Indians',
       'Kings XI Punjab', 'Kochi Tuskers Kerala',
       'Royal Challengers Bangalore', 'Gujarat Titans', 'Punjab Kings',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Pune Warriors',
       'Rajasthan Royals', 'Sunrisers Hyderabad', 'Lucknow Super Giants',
       'Deccan Chargers', 'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant'], dtype=object)

In [28]:
team_name_map = {
    "Delhi Daredevils": "Delhi Capitals",
    "Kings XI Punjab": "Punjab Kings"
}

df["Bat First"] = df["Bat First"].replace(team_name_map)
df["Bat Second"] = df["Bat Second"].replace(team_name_map)
df["Winner"] = df["Winner"].replace(team_name_map)

In [31]:
df['Batter'].unique()

array(['Rd Gaikwad', 'Dp Conway', 'Am Rahane', 'S Dube', 'Ra Jadeja',
       'Ms Dhoni', 'N Jagadeesan', 'Sp Narine', 'Vr Iyer', 'N Rana',
       'Jj Roy', 'Rk Singh', 'Ad Russell', 'D Wiese', 'Ut Yadav',
       'Cv Varun', 'Gc Smith', 'Nv Ojha', 'Sa Asnodkar', 'Yk Pathan',
       'La Carseldine', 'As Raut', 'Sk Warne', 'Sm Harwood', 'M Vijay',
       'Ml Hayden', 'Sk Raina', 'S Badrinath', 'Jdp Oram', 'Rg Sharma',
       'Q De Kock', 'Sa Yadav', 'Ss Tiwary', 'Ka Pollard', 'Hh Pandya',
       'Kh Pandya', 'Nm Coulter-Nile', 'J Yadav', 'Jj Bumrah', 'Pp Shaw',
       'S Dhawan', 'Spd Smith', 'Rr Pant', 'Ss Iyer', 'Ar Patel',
       'So Hetmyer', 'R Ashwin', 'Lmp Simmons', 'Pa Patel', 'At Rayudu',
       'Harbhajan Singh', 'J Suchith', 'Dr Smith', 'F Du Plessis',
       'Mek Hussey', 'Dj Bravo', 'P Negi', 'Mm Sharma', 'A Nehra',
       'G Gambhir', 'V Sehwag', 'Tm Dilshan', 'Mf Maharoof',
       'Shoaib Malik', 'Se Marsh', 'Jr Hopes', 'Yuvraj Singh',
       'La Pomersbach', 'Dpmd Jayawardene', 'Fy Fazal', 'R Dravid',
       'Sr Watson', 'Al Menaria', 'Pr Shah', 'Aa Chavan', 'Sw Tait',
       'Nd Doshi', 'Bb Mccullum', 'Bj Hodge', 'Ch Gayle', 'V Kohli',
       'Ubt Chand', 'Da Warner', 'Y Venugopal Rao', 'Lrpl Taylor',
       'Ik Pathan', 'Ca Ingram', 'Kma Paul', 'R Tewatia', 'Bcj Cutting',
       'Mj Mcclenaghan', 'Rasikh Salam', 'Abhishek Sharma',
       'Ks Williamson', 'Ra Tripathi', 'Ak Markram', 'N Pooran',
       'Washington Sundar', 'Shashank Singh', 'M Jansen', 'Wp Saha',
       'Shubman Gill', 'Da Miller', 'A Manohar', 'Rashid Khan',
       'Kp Pietersen', 'Nltc Perera', 'M Vohra', 'Gj Maxwell',
       'Ma Agarwal', 'Jm Bairstow', 'Ls Livingstone', 'Jm Sharma',
       'M Shahrukh Khan', 'Of Smith', 'Ishan Kishan', 'D Brevis',
       'Tilak Varma', 'Jd Unadkat', 'M Ashwin', 'Ts Mills', 'L Ronchi',
       'St Jayasuriya', 'Rv Uthappa', 'Sm Pollock', 'Am Nayar',
       'Ma Khote', 'M Manhas', 'Sv Samson', 'Str Binny', 'R Bhatia',
       'Jp Faulkner', 'Tg Southee', 'Ds Kulkarni', 'Pv Tambe',
       'Rs Bopara', 'K Goel', 'Kc Sangakkara', 'T Kohli', 'Pp Chawla',
       'Re Levi', 'Dj Jacobs', 'Kd Karthik', 'Cj Mckay', 'Rp Singh',
       'Pp Ojha', 'Mm Patel', 'Jc Buttler', 'D Padikkal', 'Dj Mitchell',
       'R Parag', 'Ta Boult', 'Th David', 'Dr Sams', 'Mk Tiwary',
       'Jp Duminy', 'Nj Maddinson', 'Km Jadhav', 'Rv Gomez',
       'R Vinay Kumar', 'Rr Powar', 'Ms Bisla', 'Jh Kallis', 'Ejg Morgan',
       'Shakib Al Hasan', 'B Lee', 'Iqbal Abdulla', 'L Balaji', 'Kk Nair',
       'Dj Hooda', 'J Theron', 'Jd Ryder', 'Sc Ganguly', 'Ad Mathews',
       'Y Nagar', 'M Morkel', 'Ac Gilchrist', 'Hh Gibbs', 'Aa Bilakhia',
       'Tl Suman', 'Shoaib Ahmed', 'Ab De Villiers', 'Ybk Jaiswal',
       'Dhruv Jurel', 'Mm Ali', 'Ja Morkel', 'Sn Thakur',
       'Anmolpreet Singh', 'Af Milne', 'Rd Chahar', 'B Chipli',
       'W Jaffer', 'Misbah-Ul-Haq', 'Mv Boucher', 'P Kumar', 'Vvs Laxman',
       'Shahid Afridi', 'Sb Styris', 'Sb Bangar', 'As Yadav',
       'Mj Guptill', 'Mc Henriques', 'D Pretorius', 'Kl Rahul',
       'Mk Pandey', 'E Lewis', 'A Badoni', 'Ba Stokes', 'Aj Turner',
       'Se Rutherford', 'Ca Pujara', 'Gj Bailey', 'R Dhawan',
       'Mg Johnson', 'Sandeep Sharma', 'Ca Lynn', 'M Markande',
       'C De Grandhomme', 'Mandeep Singh', 'Tm Head', 'Sachin Baby',
       'S Aravind', 'Ys Chahal', 'A Choudhary', 'Pk Garg', 'R Shepherd',
       'B Kumar', 'Umran Malik', 'Pn Mankad', 'Dj Hussey',
       'Gurkeerat Singh', 'Azhar Mahmood', 'R Sathish', 'Rj Harris',
       'P Awana', 'Pj Cummins', 'Kl Nagarkoti', 'S Gopal', 'Jc Archer',
       'Kartik Tyagi', 'Vr Aaron', 'Mohammad Nabi', 'Basil Thampi',
       'S Kaul', 'Mustafizur Rahman', 'Rr Rossouw', 'Sn Khan', 'Hv Patel',
       'Ma Starc', 'Harpreet Singh', 'Nl Mccullum', 'R Sharma', 'J Botha',
       'Mj Lumb', 'Aa Jhunjhunwala', 'Hc Brook', 'Gd Phillips',
       'Abdul Samad', 'Au Rashid', 'Mp Stoinis', 'V Shankar',
       'Sw Billings', 'Dl Chahar', 'B Sai Sudharsan', 'Cl White',
       'Bb Samantray', 'Mj Clarke', 'Mn Samuels', 'Sr Tendulkar',
       'Db Das', 'R Mclaren', 'Md Mishra', 'A Symonds', 'Mr Marsh',
       'B Sumanth', 'Wpujc Vaas', 'Pd Collingwood', 'A Mishra',
       'S Vidyut', 'Sp Fleming', 'Ck Kapugedera', 'Cj Ferguson', 'S Rana',
       'Wd Parnell', 'Sp Goswami', 'Jpr Scantlebury-Searles', 'Aj Finch',
       'Aj Tye', 'Bb Sran', 'Abishek Porel', 'Aman Hakim Khan',
       'Kuldeep Yadav', 'A Nortje', 'Dt Christian', 'Kb Arun Karthik',
       'Rt Ponting', 'Ch Morris', 'B Laughlin', 'Oc Mccoy', 'Ms Wade',
       'Hm Amla', 'Ad Nath', 'Djg Sammy', 'Kv Sharma', 'Sm Curran',
       'Ns Naik', 'Ap Tare', 'Rm Patidar', 'Fazalhaq Farooqi',
       'Anureet Singh', 'Karanveer Singh', 'Mohammed Siraj', 'Dr Shorey',
       'Dw Steyn', 'Kw Richardson', 'Oa Shah', 'Kk Cooper', 'Pc Valthaty',
       'Bipul Sharma', 'Harmeet Singh', 'Sunny Singh', 'Sl Malinga',
       'Cj Anderson', 'Ir Jaggi', 'Db Ravi Teja', 'I Sharma',
       'A Ashish Reddy', 'Gh Vihari', 'Jds Neesham', 'Cj Jordan',
       'Dj Harris', 'Smsm Senanayake', 'P Simran Singh',
       'Mujeeb Ur Rahman', 'Mohammed Shami', 'Dj Thornely',
       'S Chanderpaul', 'B Akhil', 'Lalit Yadav', 'R Powell',
       'Anirudh Singh', 'Jaskaran Singh', 'Ab Barath', 'S Sreesanth',
       'R Rampaul', 'Lj Wright', 'Ag Murtaza', 'Ic Pandey', 'Ab Dinda',
       'Jr Philippe', 'Navdeep Saini', 'Rn Ten Doeschate', 'Gb Hogg',
       'Cr Brathwaite', 'Z Khan', 'Mohammad Hafeez', 'Lr Shukla',
       'Ab Agarkar', 'M Kartik', 'Anuj Rawat', 'Ss Prabhudessai',
       'Shahbaz Ahmed', 'Dl Vettori', 'A Mithun', 'Kp Appanna',
       'A Kumble', 'Sohail Tanvir', 'M Kaif', 'M Rawat', 'Sk Trivedi',
       'Mohammad Asif', 'Vy Mahesh', 'Gd Mcgrath', 'Dm Bravo',
       'M Klinger', 'Ks Bharat', 'Ka Jamieson', 'Jo Holder', 'R Shukla',
       'Ad Mascarenhas', 'Tk Curran', 'S Sohal', 'Mj Santner',
       'Salman Butt', 'A Chopra', 'T Taibu', 'An Ghosh', 'N Wadhera',
       'Vishnu Vinod', 'C Green', 'Noor Ahmad', 'As Joseph',
       'Ja Richardson', 'Ut Khawaja', 'Lpc Silva', 'As Rajpoot',
       'Pbb Rajapaksa', 'Harpreet Brar', 'Rahmanullah Gurbaz',
       'Pj Sangwan', 'Sd Lad', 'Er Dwivedi', 'Ad Hales', 'Ra Bawa',
       'Tl Seifert', 'M Prasidh Krishna', 'Hf Gurney', 'Djm Short',
       'K Gowtham', 'H Klaasen', 'Nt Ellis', 'Is Sodhi',
       'Re Van Der Merwe', 'A Zampa', 'As Roy', 'Nk Patel', 'K Rabada',
       'Tu Deshpande', 'Ma Wood', 'Imran Tahir', 'Tr Birt', 'Kc Cariappa',
       'Ap Dole', 'S Badree', 'Wa Mota', 'I Malhotra', 'N Saini',
       'Dh Yagnik', 'Cm Gautam', 'Fa Allen', 'Sb Joshi', 'Ag Paunikar',
       'A Singh', 'Jm Kemp', 'Mk Lomror', 'Ankit Sharma',
       'Ramandeep Singh', 'Ds Lehmann', 'D Salunkhe', 'Nj Rimmington',
       'P Dogra', 'X Thalaivan Sargunam', 'Pankaj Singh', 'Bj Rohrer',
       'S Nadeem', 'Jec Franklin', 'Mc Juneja', 'Pa Reddy', 'S Ladda',
       'Dp Nannes', 'Bj Haddin', 'Rv Patel', 'Kk Ahmed', 'S Anirudha',
       'Cr Woakes', 'Swapnil Singh', 'K Kartikeya', 'Jp Behrendorff',
       'Ghs Garton', 'Kr Mayers', 'Sa Abbott', 'An Ahmed', 'Younis Khan',
       'Kamran Akmal', 'Hr Shokeen', 'Arshad Khan', 'Bmaj Mendis',
       'I Udana', 'Le Plunkett', 'Sp Jackson', 'Dj Willey',
       'Pwh De Silva', 'Tm Srivastava', 'Umar Gul', 'Ap Majumdar',
       'Vijaykumar Vyshak', 'Td Paine', 'Sb Wagh', 'Ac Thomas',
       'M Muralitharan', 'B Indrajith', 'Harshit Rana', 'Akash Deep',
       'Jr Hazlewood', 'J Arunkumar', 'Dt Patil', 'Abdur Razzak',
       'A Chandila', 'Abdul Basith', 'Sm Katich', 'Ac Voges',
       'Sd Chitnis', 'Crd Fernando', 'Vs Yeligati', 'Auk Pathan',
       'A Uniyal', 'Ms Gony', 'P Sahu', 'Rj Peterson', 'L Ablish',
       'Rs Sodhi', 'Gc Viljoen', 'Avesh Khan', 'S Lamichhane',
       'Ac Blizzard', 'Yv Takawale', 'Rr Raje', 'Arshdeep Singh',
       'Vg Arora', 'S Kaushik', 'Br Dunk', 'Shivam Mavi', 'C Munro',
       'Atharva Taide', 'Mw Short', 'Mn Van Wyk', 'H Das', 'Dnt Zoysa',
       'Ba Bhatt', 'D Kalyankrishna', 'Rr Sarwan', 'Ravi Bishnoi',
       'Naveen-Ul-Haq', 'Sj Srivastava', 'K Upadhyay', 'Y Prithvi Raj',
       'Kj Abbott', 'Mdkj Perera', 'Vh Zol', 'Ck Langeveldt', 'S Narwal',
       'Rk Bhui', 'Lh Ferguson', 'M De Lange', 'C Sakariya', 'K Yadav',
       'P Chopra', 'T Stubbs', 'Yv Dhull', 'Rr Bhatkal', 'Kaj Roach',
       'R Sanjay Yadav', 'A Mukund', 'Sb Jakati', 'Yashpal Singh',
       'Baw Mendis', 'Pd Salt', 'A Flintoff', 'Joginder Sharma',
       'T Thushara', 'Jj Van Der Wath', 'R Ninan', 'Yash Dayal',
       'Yudhvir Singh', 'Je Taylor', 'Rj Quiney', 'M Ntini',
       'Virat Singh', 'Md Shanaka', 'Sanvir Singh', 'Kmdn Kulasekara',
       'Vrv Singh', 'U Kaul', 'B Stanlake', 'Parvez Rasool',
       'De Bollinger', 'Sunny Gupta', 'T Banton', 'S Tyagi', 'Aa Noffke',
       'Ab Mcdonald', 'Rg More', 'T Henderson', 'Ss Shaikh',
       'J Syed Mohammad', 'C Nanda', 'F Behardien', 'Jl Pattinson',
       'Be Hendricks', 'At Carey', 'Pvd Chameera', 'Rs Gavaskar',
       'Se Bond', 'C Madan', 'Dj Muthuswami', 'He Van Der Dussen',
       'Mukesh Kumar', 'Mg Bracewell', 'Dj Malan', 'T Natarajan',
       'P Ray Barman', 'A Tomar', 'Mukesh Choudhary', 'S Sriram',
       'Sikandar Raza', 'Ks Sharma', 'Kamran Khan', 'P Parameswaran',
       'D Du Preez', 'Liton Das', 'Ya Abdulla', 'Simarjeet Singh',
       'M Theekshana', 'Vivrant Sharma', 'R Bishnoi', 'Aj Hosein',
       'Ankit Soni', 'Shivam Sharma', 'A Dananjaya', 'Vs Malik',
       'P Dubey', 'Mashrafe Mortaza', 'Ss Cottrell', 'Je Root', 'Km Asif',
       'Mohit Rathee', 'Mohsin Khan', 'S Randiv', 'Rp Meredith',
       'Jl Denly', 'Gr Napier', 'Fh Edwards', 'Pm Sarvesh Kumar',
       'Dp Vijaykumar', 'Mohammad Ashraful', 'V Pratap Singh', 'Ar Bawne',
       'Dr Martyn', 'Arjun Tendulkar', 'Kr Sen', 'Psp Handscomb',
       'Daj Bracewell', 'Shoaib Akhtar', 'Y Gnaneswara Rao', 'Ua Birla',
       'Dg Nalkande', 'T Shamsi'], dtype=object)

#### **Cleaning Player Names**

In [30]:
# Standardizing Player Names
df["Batter"] = df["Batter"].str.strip().str.title()
df["Non Striker"] = df["Non Striker"].str.strip().str.title()
df["Bowler"] = df["Bowler"].str.strip().str.title()
df["Player Out"] = df["Player Out"].str.strip().str.title()

### **Handling Missing & Duplicated Data**

#### **Identifying Missing values**

In [36]:
df.isna().sum()

Match ID                        0
Date                            0
Venue                           0
Bat First                       0
Bat Second                      0
Innings                         0
Over                            0
Ball                            0
Batter                          0
Non Striker                     0
Bowler                          0
Batter Runs                     0
Extra Runs                      0
Runs From Ball                  0
Ball Rebowled                   0
Extra Type                      0
Wicket                          0
Method                     227866
Player Out                 227866
Innings Runs                    0
Innings Wickets                 0
Target Score                    0
Runs to Get                123927
Balls Remaining                 0
Winner                          0
Chased Successfully             0
Total Batter Runs               0
Total Non Striker Runs          0
Batter Balls Faced              0
Non Striker Balls Faced         0
Player Out Runs            227866
Player Out Balls Faced     227866
Bowler Runs Conceded            0
Valid Ball                      0
dtype: int64



#### Observations:

* **Method** has **227,866 missing values** because it is only applicable when a wicket falls. It is **NaN for deliveries where no wicket fell**.  
* **Player Out** has **227,866 missing values** as it is recorded only when a wicket falls, making it **NaN for non-wicket deliveries**.  
* **Player Out Runs** has **227,866 missing values** because it is missing for deliveries where no player was out.  
* **Player Out Balls Faced** has **227,866 missing values** for the same reason—it is recorded only when a player gets out.  
* **Runs to Get** has **123,927 missing values** as it is **only relevant for the second innings**, making it **NaN for the first innings**.

In [40]:
# replacing missing values

df['Method'].fillna('Not Out', inplace=True)

df['Player Out'].fillna('None', inplace=True)
df['Player Out Runs'].fillna(0, inplace=True)

df['Player Out Balls Faced'].fillna(0, inplace=True)
df['Runs to Get'].fillna(0, inplace=True)

In [41]:
df.isnull().sum()

Match ID                   0
Date                       0
Venue                      0
Bat First                  0
Bat Second                 0
Innings                    0
Over                       0
Ball                       0
Batter                     0
Non Striker                0
Bowler                     0
Batter Runs                0
Extra Runs                 0
Runs From Ball             0
Ball Rebowled              0
Extra Type                 0
Wicket                     0
Method                     0
Player Out                 0
Innings Runs               0
Innings Wickets            0
Target Score               0
Runs to Get                0
Balls Remaining            0
Winner                     0
Chased Successfully        0
Total Batter Runs          0
Total Non Striker Runs     0
Batter Balls Faced         0
Non Striker Balls Faced    0
Player Out Runs            0
Player Out Balls Faced     0
Bowler Runs Conceded       0
Valid Ball                 0
dtype: int64

Check for Duplicates

In [37]:
df.duplicated().sum()

np.int64(0)

No Duplicates found

###**Data Type Corrections**

**Match ID** should be converted from **int64** to **str** because it represents a categorical value, not a numerical one.

**Date** should be converted from **object** to **datetime64** since it is needed for time-series analysis.

**Ball Reboweled** should be converted from **int64** to **bool** by mapping 1 → True and 0 → False.

**Runs to Get** should be converted from **float64** to **int64** because runs are always whole numbers.

**Player Out Runs** should be converted from **object** to **int64** because it should be a numeric column.

**Player Out Balls** Faced should be converted from **float64** to **int64** because it should be an integer.

In [42]:
# Convert Match ID to string
df['Match ID'] = df['Match ID'].astype(str)

# Convert Date to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Convert Ball Rebowled to boolean
df['Ball Rebowled'] = df['Ball Rebowled'].astype(bool)

# Convert Runs to Get to integer
df['Runs to Get'] = df['Runs to Get'].astype(int)

# Convert Player Out Runs to integer
df['Player Out Runs'] = df['Player Out Runs'].astype(int)

# Convert Player Out Balls Faced to integer
df['Player Out Balls Faced'] = df['Player Out Balls Faced'].astype(int)

## **Feature Engineering**

In [44]:
df['Year'] = pd.to_datetime(df['Date']).dt.year

df['is_six'] = (df['Batter Runs'] == 6).astype(int)

In [45]:
df['Method'].unique()

array(['Not Out', 'bowled', 'caught', 'lbw', 'stumped', 'run out',
       'caught and bowled', 'retired hurt', 'hit wicket', 'retired out',
       'obstructing the field'], dtype=object)

In [46]:
valid_methods = ['bowled', 'caught', 'lbw', 'stumped', 'caught and bowled', 'hit wicket']

df['bowler_wickets'] = df['Method'].isin(valid_methods).astype(int)

In [47]:
df['is_dot_ball'] = (
                      (df['Runs From Ball'] == 0)
                      & (df['Extra Runs'] == 0)
                      & (df['Valid Ball'] == 1)
                    ).astype(int)